title: Rebecca Chang's Website
email: 'rebeccachang2022@gmail.com'
description: My brain blurbs
url: https://rchang0.github.io/
github_username: rchang0
author: Rebecca Chang

markdown: kramdown
kramdown:
    math_engine: mathjax

#plugins:
#  - jekyll-paginate

#paginate: 10
#paginate_path: "/page/:num"

#exclude:
#  - Gemfile
#  - Gemfile.lock

theme: jekyll-theme-Chirpy